### ISSUE TITLE
Challenges firebase mockup data

### ISSUE THREAD

**Issue by osmolenko** [Illu/Pix#1]
Working on web admin panel.
You cannot create a new challenge using the app so what data must be in the firebase to display challenges?
It would be nice to see the entire data structure of the firebase because when the application is launched, only the structure of users and posts is created.

**Comment by Illu** [comment]
Challenges cannot be created or modified within the App. It's a simple Firestore Collection with 12 Documents (1 for each month: Jan, Feb, Mar, etc.). Each Document has an id (which is a string with the same value as the Document's name) and a title (also a string).

Hope this helps.
